CMake:   Fixed setting a Windows variable

diff --git a/install/build b/install/build
--- a/install/build
+++ b/install/build
@@ -24,6 +24,11 @@ if [ -z "$ROOT" ]; then
     exit 1
 fi
 
+if [ ! -d "$ROOT/modules/juce/modules" ]; then
+    echo "ERROR: juce library module not preset!"
+    exit 1
+fi
+
 echo "\n=========================================="
 echo ROOT: "$ROOT"
 echo CMAKE_BUILD_DIR: "$CMAKE_BUILD_DIR"
